import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :partners, PartnersWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# PayPal configuration for production
config :partners, Partners.Services.Paypal,
  mode: :live,
  base_url: "https://api-m.paypal.com",
  # More restrictive timeout in production
  request_timeout: 15_000

# Credentials and webhook IDs will be set in runtime.exs

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
